### ISSUE TITLE
Incorrect window size

### ISSUE THREAD

**Issue by muddymole** [neutralinojs/neutralinojs#1020]
In "window" mode, when setting the window size - either using the setSize function or the settings in neutralino.config.json - the window is incorrectly sized.

For example, when using the unmodified minimal template, which _should_ set the window size to 800x500, the actual window size (as measured using a graphics app) is 786x493 (outer) / 784x461 (inner).

When retrieving the sizes using JS, I get:
window.outerWidth/Height: 784x461 // ignores the window frame
window.innerWidth/Height: 784x461 // accurate, but not the 800x500 we wanted
Neutralino.window.getSize(): 800x500 // the size we wanted, but not the size we actually get

**Specifications**  
 - OS: Windows 10 x64
 - Neutralinojs version: v4.7.0
 - Neutralinojs client library version: v3.6.0
 - Neutralinojs CLI version: v9.3.1

**Additional context**
The Discord user "Squadrobot" reported exactly the same problem on 29/05/22 -
"_Hmm.. Neutralino.window.setSize is not working as expected for me.
After calling Neutralino.window.setSize({width:800,height:600}) the inner size of the window becomes 784x561 and outer size:  786x593.  Anyone else noticed?_"

It may perhaps be related to the Windows 10 scaling settings in some way, as changing this gives different (but still wrong) results.

**Comment by parteekcoder** [comment]
can you please assign me this issue

**Comment by jouni-kantola** [comment]
This issue still exists in 4.14.1 and seems to be related to not accounting for Windows scaling. The problem is worsened with more zoom which results in content not being in the viewport when starting the application.

When I use recommended settings 250 % the Neutralinojs minimal template app starts with the following window dimensions:
```
window.innerHeight: 165
window.innerWidth: 308
```
<img src="https://github.com/neutralinojs/neutralinojs/assets/2670127/a1fec332-6482-4c40-8893-934e3bf81202" alt="Neutralinojs window size too small, not fitting all content when using Windows scaling 250 %">


If I change scaling to 100 % this is how the app looks.
```
window.innerHeight: 461
window.innerWidth: 784
```
<img src="https://github.com/neutralinojs/neutralinojs/assets/2670127/b39da353-4d62-44b5-8c97-b5bbce7e545a" alt="Neutralinojs fits all content when using Windows scaling 100 %">

**Comment by jouni-kantola** [comment]
@shalithasuranga Do you consider OP and Neutralinojs window size being too small at startup in Windows the same issue?

**Comment by shalithasuranga** [comment]
We are linking this issue to the main #648. Thanks so much for reporting and discussing :tada:
