### ISSUE TITLE
Compiling Neutralinojs fork via GitHub Actions workflows

### ISSUE THREAD

**Issue by lexesv** [neutralinojs/neutralinojs#1067]
Hello!

I get an error when creating a Release (screenshot)

What am I doing wrong?

![image](https://user-images.githubusercontent.com/15149258/217581734-56c4e49f-23f9-4d18-8d93-20ca2205edbc.png)

**Comment by shalithasuranga** [comment]
Hi.. This error is occured because the CHANGELOG.md file isn't modified. You can either update the changelog or use `--no-changes` with the ReleaseZri script execution in the GitHub Actions workflow.

Check the [nightly release workflow](https://github.com/neutralinojs/neutralinojs/blob/9ce945a6a9a2725040da980d4775d814ded28a6a/.github/workflows/nightly_release.yml#L146) and the [ReleaseZri project docs](https://codezri.org/docs/releasezri/intro) for more information.

Thanks
