### ISSUE TITLE
importing external js modules

### ISSUE THREAD

**Issue by blurymind** [neutralinojs/neutralinojs#132]
Is it possible to require or import library js files? If so, how?

**Comment by shalithasuranga** [comment]
Yes. you can use any client side js libraries with Neutralino. Place your js source files to `app/assets` and import to html
eg:- 
```js
<script src="/assets/app.js"></script>
```
But since there is no node runtime, node packages with `require` cannot be used.

**Comment by pegvin** [comment]
you need to understand how this works, modules in `node_modules` folder are useless for NeutralinoJs or Any other browsers because `nodejs` knows how to resolve those modules, but the browser doesn't know it.

For Example assume you have a module `xyz` installed and it's in the `node_modules` folder, when you `require('xyz')` nodejs uses it's module resolution algorithm to find that module in the `node_modules` folder but browsers or neutralinojs or even electron isn't built that way, they don't know where the module `xyz` is.

So For this purpose we use module bundlers, the main work of a module bundler is take a javascript file, resolve all the modules and put them in that file (also known as a `bundle`).

These Are Some Videos I'd Recommend You Watch:
- [From IIFEs to CommonJS to ES6 Modules](https://youtu.be/qJWALEoGge4)
- [Module Bundlers Explained](https://youtu.be/5IG4UmULyoA)
