### ISSUE TITLE
'neu build' fails when "documentRoot" is "/" although 'neu run' works correctly

### ISSUE THREAD

**Issue by rmzetti** [neutralinojs/neutralinojs#1326]
**Describe the bug**
I have several static sites where index.html is in the site folder root /, & javascript files in /lib/, etc.
In neutralino.config.json, if I set "documentRoot": "/" and "url": "/", 'neu run' works fine showing the site locally as expected, but if I try to do a dist build with 'neu build', the build fails with: neu: ERRR Error: Cannot copy './' to a subdirectory of itself, '.tmp/'

**To Reproduce**
1. Run 'neu create myapp' in a folder - it creates neutralino.config.json with "documentRoot":"/resources/", & "url":"/"
2. In the '/' folder of myapp, move the contents of '/resources/' up to '/', and delete the '/resources/' folder
3. In 'neutralino.config.json' change "documentRoot":"/resources/" to "documentRoot":"/", and change the other occurrences of "/resources/" to "/".
4. **Note** that after the changes "neu run" runs the app locally as expected.
5. But "neu build" fails quickly with "neu: ERRR Error: Cannot copy './' to a subdirectory of itself, '.tmp/' "

**Expected behavior**
Expected the build to complete.

**Specifications**  
 - OS: Windows 11 x64 ver 10.0.26120
 - Neutralinojs binaries: 5.4.0 (latest)
 - Neutralinojs client: 5.4.0 (latest)
 - Neutralinojs CLI version: 11.3.0 (latest)

**Additional context**
I have several sites in different folders, which I can load locally using a live server, or use nwjs to load as a local app, as I can with neutralinojs using "neu run". But I'd like also to be able to create neutralino dists without having to restructure my site folders.

**Comment by ArbajAnsari19** [comment]
# Explanation of Why This Happens

When you run `neu build`, Neutralino follows these steps:

1. Creates a temporary build directory (`.tmp/`).
2. Copies all files from the `documentRoot` directory to this temporary directory.
3. Processes these files and creates the final distribution.

---

## When `documentRoot` is set to `/`:

- The `/` refers to your entire project root directory.
- This includes **ALL** files and directories in your project, such as:
  - The `.tmp` directory itself (once created).
  - Any build artifacts.
  - The `.neu` directory.
  - Node modules (if any).
  - Git files.
  - etc.

---

## Why the Error Happens:

When Neutralino tries to copy `/` into `.tmp/`, it essentially tries to copy:

```plaintext

FROM

myapp/                  # Your root directory (/)
├── .tmp/               # Build directory
│   └── (build files being created)
├── .neu/
├── index.html
├── js/
├── lib/
└── neutralino.config.json


INTO

myapp/
 ├── .tmp/          # Trying to copy everything including .tmp in
 │   ├── .tmp/      # This creates an infinite recursion
 ├── .neu/
 ├── index.html
 ├── js/
 ├── lib/
 └── neutralino.config.json

```

_This is why you get the error "Cannot copy './' to a subdirectory of itself, '.tmp/'". It's a protection against recursive copying that would otherwise create an infinite loop._

**SOLUTION :**
 Using a subdirectory like /src for your web files, you create a clean separation between:
Your application files (in /src)
Build-related files and directories (in project root)
This allows the build process to safely copy only your application files without getting into a recursive copy situation.


Hope you got you answer, 
thanks.



@shalithasuranga Please close this issue if you find the solution to be helpful and It resolved this issue.

**Comment by rmzetti** [comment]
Thanks for your very clear explanation and for your time. I would have thought, though, when it comes to copying the build created in .tmp it would be correct to copy over the old .tmp folder, not into it - it is a .tmp after all!
Since I'm directly comparing Neutralino to other approaches (specifically nwjs and electron) by setting up the folder/site so that it will run locally using all three approaches (as well as via live server and as a remote site). Neutralino will have to stay with 'Neu run' to start, which may well mean it is perceived to be slower than it needs to be.. but I understand from your reply that things will stay as they are so I guess that's life!
