### ISSUE TITLE
Add edgeChromium for Neutralino Windows instead IE

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#147]
Currently webview header file gives IE for Windows. There is an ongoing **[discussion]()** to add EdgeHTML

**Comment by apollolux** [comment]
Any chance that this can be updated to use an Edge Chromium webview on Windows if present and/or some sort of "toggle engine" Edge vs Edge Chromium setting or parameter?

**Comment by apollolux** [comment]
A recent article on using WebView2 for Edge Chromium usage on Windows: https://blogs.windows.com/msedgedev/2019/12/11/webview2-interactive-api-sample/

**Comment by dougreichard** [comment]
Thanks for creating this, I was looking into webview and building something similar. Please stop using IE at all as soon as possible it is garbage. This project has so much promise as a wrapper for webview adding the server aspect, but it is unusable in for standalone apps on windows due to incompatibilities. It actually took a bit to figure this out, because it works fine for browser and debugging with devtools. But it wasn't clear at all why it wasn't working in window mode until I realized it was IE. WebView has Edge and EdgeChromium support in the works on their master. For others having the same issue, at least you can develop and debug using browser mode until support is added for window/standalone. Maybe update your docs tell of which browser is used on each platform.

**Comment by sheerun** [comment]
DeskGap is can use Edge on Windows, maybe it will help here? https://github.com/patr0nus/DeskGap/

**Comment by apollolux** [comment]
I finally started looking into the upcoming WebView2 and some into what DeskGap does.

First and foremost, there is a *lot* of boilerplate for getting the old Trident-based MSHTML stuff working, and DeskGap's implementation of *that* is almost the same as Neutralino's, but theirs is more C++ looking.

Second, the Edge implementation they use is *very* WinRT-heavy, and so far I'm not seeing a clean way to mimic what they do to make that happen without likely breaking compatibility with Windows 7. If Win7 compatibility is no longer a concern for Neutralino then I don't see a problem doing what they do for an Edge-based webview.

Third, the upcoming Edge Chromium WebView2 library (still technically in prerelease as of June 2020) is apparently very Visual Studio oriented in its distribution and usage, and its available sample projects on GitHub rely HUGELY on using VS2017 or later to make things happen. Neutralino doesn't even compile out-of-the-box on Windows with a VS toolchain, free or otherwise! (This particular bit is a separate issue I'll open shortly) The samples make it look suspiciously simple to implement, but I'm pretty sure a *lot* of magic is going on that might require using VS to work properly; finding the location of the winrt headers needed by WebView2, for example, is not guaranteed when compiling with gcc, and one particular path VS seems to use for me is C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt\ for includes like EventToken.h from the WebView2 header and I don't rightly know how the project chose that location.

These are my findings so far when attempting to reconcile the removal of IE11 webview on Windows in favor of newer, ES6-and-later-friendly solutions.

**Comment by ngbrown** [comment]
@apollolux I vote that Windows 7 compatibility is no longer an issue.  People really shouldn't be running it with connectivity to the Internet.

+1 for compiling with Visual Studio on Windows.

**Comment by Zireael07** [comment]
@ngbrown: People are running Windows **XP** with internet connectivity... My older laptop has Windows 7 and still sees occasional use, and I know people who don't want to switch to 10 due to perceived privacy issues...

**Comment by sheerun** [comment]
Windows 7 is already past End of Life. If someone wants to support legacy OS then he/she can use Electron...

**Comment by dougreichard** [comment]
Personally, I would be looking for a tool that stays current and isn't supporting outdated insecure browsers. I would be fine with removing support for unsupported systems in order to make a relevant smaller tool. Since this tool is attractive as being **smaller** I would encourage the maintainers to keep the master branch small, keep it relevant. If people need prior OS that are no longer updated, they can fork the older branch that has that support.

**Comment by antoniassiph** [comment]
> Windows 7 is already past End of Life. If someone wants to support legacy OS then he/she can use Electron...

Just a note on this topic, I have a huge client with many "windows XP only" apps and I can't say "throw all your expensive and useful apps away and update your OS". Electron does not support XP and NW.js creates a 200MB app (distribute it in some locations are almost impossible).
Supporting both would be nice. Maybe a `neu-cli` flag ou 2 SDK versions (like NW i guess)?

**Comment by apollolux** [comment]
A week and a half or two weeks ago I asked an internet buddy to help me look into this because he had mentioned that he was playing around with getting WebView2 working in Go. He had come up with [WebView2 in MinGW](https://github.com/jchv/webview2-in-mingw) because I had told him my biggest obstacle to getting this working myself was how much VS "magic" was involved and the reliance on Nuget etc and being configured as a full-on VS solution where Neutralino is strictly non-VS, for better or worse. So far working pretty well playing around with just his code, but I think this would help considerably in getting WebView2 into Neutralino pretty decently.

Doesn't handle the issue of integrating EdgeHTML without using WinRT but [webview/webview](https://github.com/webview/webview) might help in that respect.

**Comment by paulocoghi** [comment]
@antoniassiph, the problem I see with win7 support is the extra maintenance work

**Comment by bisubus** [comment]
Not supporting Windows 7 may be not a big issue but to be clear:
```js
IE !== Win7
```
The newest Windows 10 LTSC has IE 11 bundled, not Edge. Deliberately not supporting something that was meant for long-term use doesn't feel right.

**Comment by shalithasuranga** [comment]
Hey all.. I enabled EdgeHTML/Chromium by using the latest webview library. The compilation was not successful with mingw. However, I have a working version with the MSVC compiler on https://github.com/neutralinojs/neutralinojs/tree/experiment/webview-edge-win Maybe you guys can take a look. 

But we have a problem with UWP security protocols seems. It won't work until we run the following command with admin rights

```
CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"
```
Ref: https://github.com/webview/webview/issues/410

So, every user needs to run this on Windows to get Neutralino app working seems.

**Comment by shalithasuranga** [comment]
Hm.. this took some time. But finally, it is done 😄
