### ISSUE TITLE
OSX support ETA?

### ISSUE THREAD

**Issue by lacymorrow** [neutralinojs/neutralinojs#152]
💃

**Comment by kasvith** [comment]
Will be ready in next week

**Comment by SirWindfield** [comment]
Hey! I already pushed a PR for OSX support! It would even allow us to move all platform dependent code to one code base, Rust. Take a look here: https://github.com/neutralinojs/neutralinojs/pull/170

**Comment by kasvith** [comment]
That seems good.

Anyway, I worked on the other way implementing macOS support with C/C++. It does simply adds MacOS support(95% completed, only need to add open/save dialogues for the platform and good to go). 

Also, I decided to clean up and merge all common platform-independent code together in another PR. This will reduce code duplication and allow us to work in a single codebase which compiles natively for each platform(we will use compiler preprocessors to handle platform-dependent code).

**Comment by SirWindfield** [comment]
I feel like we should decide whether we'll use your code base or mine before putting more effort into it. Mine is based on Rust. It misses cloud and browser support but can already be compiled for all three OSs.

Yours sounds good too tbh. It's up to @shalithasuranga which he prefers though.

The big improvements rust would give us are no platform dependent code all together. It's one code base, one language. I personally prefer it over C/++ because it checks during compilation for memory errors using its checker :) but this one is just my two cents.

As I said, there is no need to put effort on two sides into the same problem. We should probably wait until we know which way to go.

I guess I have my own vision of neutralinojs in my mind. After doing some analysis of popular open source electron apps I noticed that 90% of their calls are to the same 3 modules. Implementing those core functionalities would actually allow a lot of lightweight alternatives to rise.
I wouldn't mind if your code gets added to the repo. I might actually start working on something similar like neutralinojs in the end as I like the idea but would probably try to mimick nodejd core functionality (I.e. Those 3 modules).

**Comment by kasvith** [comment]
@SirWindfield yeah I like rust too, it narrows down 3 codebases to a single one and I like the functional like syntax.

Even if we used compiler preprocessors it won't look that nice as Rust IMO.

But you mentioned a very good point, NodeJS needs to be analyzed and we need to capture most common syscalls used for applications +1 for that

**Comment by kasvith** [comment]
Anyway does rust support calling C/C++ interfaces directly? Most platform-dependent UI codes are written with C/C++ and Objective-C and they will be needed as well.

**Comment by SirWindfield** [comment]
@kasvith I used to crates to allow the native UI part, `web-view` to call the same library that this project uses and `nfd` (native file dialog) which allows to show and retrieve the results of open/save dialogs using Rust code.

But yes, you can call C/++ code from Rust. There are even crates making it easier for you without writing binding code. `winapi` basically implements the Windows API in Rust, allowing you to write Windows code from Rust. Similar crates exist for Linux and OSX as well. I doubt that we need to call C/++ any time soon though. The UI part can be done directly in Rust with the two crates mentioned above.

Anyway...

I mean, I didn't write the most clean Rust code ever but I wanted to keep it easy so that people who do not know Rust grasp the idea of the code easily.
If you are fine with using Rust, what would you say about going with my idea? I can polish my analysis a bit up and post it down the week in a clean format. We could then go and try to come up with some API scheme that we than implement cleanly.

**Comment by kasvith** [comment]
We would let @shalithasuranga to decide which way to move, but please do your analysis :) It would help a lot IMO

**Comment by SirWindfield** [comment]
No problem, I'll post the results during the next week or so. I'm fine with that :)

**Comment by SirWindfield** [comment]
@kasvith https://gist.github.com/SirWindfield/e9ecb43762e740d63532179b238bf95a
I am a `jq` noob and couldn't get the function names sorted by value. Googled for like 10 minutes and wasn't able to do so.

The number represents the number of times the function has been used within the code. However, it doesn't represent the number of times the function actually got called. For example, if you have a `settings.js` file that calls `fs.writeFile` within a `saveSettings` function and other modules call that function, the call count would still be 1. 

I retrieved those values by parsing js/ts code using an AST. But I couldn't really figure out a way to map function calls like `saveSettings` to module calls like `fs.writeFile`. I can upload the node if you cant though. Maybe you figure it out :smile:

**Comment by kasvith** [comment]
By looking at it in first glance i guess we need to implement most for fs and os. We lack most of the parts still. 

Since we already have a native browser engine most other fn calls will be work inside browser like opening a connection to a website.


Also I guess we would need to narrow down the scope of the product.(With current setup we would not be able to provide all general programming concepts)

CC @shalithasuranga

**Comment by SirWindfield** [comment]
I was thinking about this for some time. PWAs really start to get popular right now and they offer a lot of functionality that normal web applications don't (notifications, intents, clipboard access etc.). 

What if we design this project to complement them? Like, making enhanced PWAs. Giving them more features than they have right now without the need to run a whole Electron framework on the client side. We could for example offer direct file access over the protocol so that PWAs can really work with user files. Another example would be running native commands. 

Giving all that, we definitely need a permission system similar to Android's that the user can use to remove functionality. Direct file access for example could be then limited to a specific folder only. Running commands could be scoped to specific ones only too.

This would put the project in a position where it would be a unique alternative I guess. I do not have the time right now to test if PWAs work within neutralinojs. Would you mind testing it out, out of curiosity? You could just load this project into neutralinojs: 

https://github.com/gokulkrishh/demo-progressive-web-app
https://demopwa.surge.sh/

**Comment by kasvith** [comment]
But actually since neutralino ships html/css/js with it i don't see the usage of having PWAs with this(also since we use system webviews i dont think all supports PWA at same level for example IE11).

Anyway neutralino provides similar functionality imo. But first I guess we need to provide the features of PWA via API like notifications etc :)

**Comment by kasvith** [comment]
Anyway we shall start a new thread :)

**Comment by shalithasuranga** [comment]
Closing this since we have a working version of neutralino on mac
