### ISSUE TITLE
How to run command with auth?

### ISSUE THREAD

**Issue by jardenliu** [neutralinojs/neutralinojs#177]
If I run command with auth (such as `sudo reboot`), how can i Input password for authorization.

**Comment by kasvith** [comment]
Which OS?

**Comment by jardenliu** [comment]
@kasvith macOS

**Comment by shalithasuranga** [comment]
@jardenliu  Did you try neutralino with sudo?

**Comment by jardenliu** [comment]
sometime double click to start it.

**Comment by kasvith** [comment]
Need to check that, could you please provide steps

**Comment by jardenliu** [comment]
![image](https://user-images.githubusercontent.com/15191056/65751788-0800c180-e13e-11e9-8968-55a581da55b8.png)
add the `Neutralino.os.runCommand` into app.js, and run application

**Comment by bmcgonag** [comment]
I use the command like this

`Neutralino.os.runCommand('echo < your sudo password here > | sudo -S reboot',`

This avoids the prompt for the super user password at the time you run it.

**Comment by shalithasuranga** [comment]
I recently tested this scenario on mac and it works.. if you need to run `x` command with `sudo`, please run Neutralino binary with `sudo` privileges. After than simply `execCommand` with `x`.

But you are trying to launch Neutralino without root access and trying to pipe your password to sudo, please do it at your own risk. It is not the recommended way because you are exposing your password. However, it's totally okay if you are doing some experiments with virtual machines.

**Comment by Vampire-Offical** [comment]
i want to run my app as administartor how can i do it
