### ISSUE TITLE
need app icon

### ISSUE THREAD

**Issue by acedigibits** [neutralinojs/neutralinojs#207]
i have basic html5 app that doesnt need any OS APIs . Hence this repo is perfect for build as this gives low ram and disk use. 

Only requirement remaining is to have a app icon. without this it looks very unprofessional.

**Comment by compelx** [comment]
I realize this has been open for a bit but I ran into this issue today and thought I'd share.
If you're on Windows you can use Resource Hacker to add a icon (.ico) to the executable. It will spit out a modified binary with the icon.

http://www.angusj.com/resourcehacker/

**Comment by shalithasuranga** [comment]
Iconfile supported was added to all platforms. will be released with v1.5.0 soon

**Comment by WilliamAlecBrannon** [comment]
I have updated to the current available version using neu update, and am trying to get the app icon to work. I followed the suggestion from the website to use a transparent png and it works for the taskbar, and the browser favicon, but the .exe for windows (and the other distributions, but windows is specifically the one im targetting) still shows as an exe with no set icon so it grabs windows' default application icon. According to resource hacker, the distribution has no icon associated with the exe at all. Binary version is 2.5.0 and client version is 1.2.0, and idk which the milestones are tracking

**Comment by pegvin** [comment]
Currently Neutralino doesn't embed icons when building but we'll add it soon.

**Comment by DevilishDante** [comment]
Hello how about this function?

**Comment by AxDSan** [comment]
Still waiting for this...

**Comment by tiagorangel2011** [comment]
Any update?

**Comment by russellweed** [comment]
Those still waiting on official support may appreciate this workaround I've incorporated into my build process.

What you'll need to do is download an old app called [Resource Hacker](http://www.angusj.com/resourcehacker/), which is from the old Visual C++ WinForms days (because that's *still* how Windows does it). Essentially what you need to do is make your build and use ResHacker to replace the ICO file after the fact. You will also probably want to replace the metadata (Application Name, Company Name, Copyright, etc.) - this is the stuff that appears when you view the files Properties (and is used elsewhere in the OS; in my case it's used by the browser when it tries to open protocol handler links).

Of course doing this by hand got to be a pain in the ass, so I amended my `npm build` command to run a batch file to do all this for me.

```json
"build": "npm --prefix react_folder run build && neu update && neu build --release && build-reshack.bat && build-cleanup.bat"
```

I went w/ a batch file becasue, while ResHacker has command line parameters, it is kind of picky about them, and I found it much easier to just put them all in a batch file and do it that way. (If you're unfamiliar, .bat files are kind of like the MS-DOS/Windows equivalent of .sh scripts)

Here is my **reshack.bat**, wherein it opens the EXE from my build, saves it as a different EXE, and adds ICONS and VERSIONINFO (metadata) from a resource file (Resources.res) in my project

```bat
@ECHO OFF
CALL "%PROGRAMFILES(X86)%\Resource Hacker\ResourceHacker.exe"^
 -log CONSOLE^
 -open "%CD%\dist\project_name\project_name-win_x64.exe"^
 -save "%CD%\dist\project_name\project_name.exe"^
 -action addoverwrite -res "%CD%\Resources.res" -mask ICONGROUP,PROJECT_NAME,0
CALL "%PROGRAMFILES(X86)%\Resource Hacker\ResourceHacker.exe"^
 -log CONSOLE^
 -open "%CD%\dist\project_name\project_name.exe"^
 -save "%CD%\dist\project_name\project_name.exe"^
 -action addoverwrite -res "%CD%\Resources.res" -mask VERSIONINFO,1
```

Note that it requies two calls; one for adding the icon and another for adding the version. I couldn't figure out how to do both at the same time so I said screw it and just do it twice. Doesn't really matter for something like this.

Resources.res is a "Resource" file you can create w/ Resource Hacker that is basically the same binary blobs of icon data and versioninfo (metadata) you can save directly to an exe, except saved to a .res file instead. You can then "apply" the .res file to your EXE. Commit this to your git repo (mine is in the root folder) as you'll want to track changes to it, even though it is a binary.

You can use Resource Hacker to edit the .res file and increment version number or change icons as needed in the future, save it, then just rebuild you app.

The result is a completely proper exe w/ icon and metadata (at least as far as I can tell)

![image](https://github.com/neutralinojs/neutralinojs/assets/1160446/a3f52240-d1d4-42ca-955c-ef89b26c52b7)

**Comment by hschneider** [comment]
I use this call with Resource Hacker, which overwrites the original file:
```
"c:\Program Files (x86)\Resource Hacker\ResourceHacker.exe" -open test.exe -save test.exe -action addskip -res icon.ico -mask ICONGROUP,MAINICON,
```

**Comment by hschneider** [comment]
Just released v1.0.2 of my Neutralino Build-Scripts

New in build-win.sh:
- appIcon can be defined
- If defined, a Windows script is created, which calls Resource Hacker.
- Double-clicking this script adds the icon to the .exe-file and deletes the .ico-file and itself afterwards.

So adding an icon to a Windows built is as easy as 1 double-click on the Windows machine  🙂

https://github.com/hschneider/neutralino-build-scripts

**Comment by CosmoMyzrailGorynych** [comment]
https://www.npmjs.com/package/resedit-cli adds an icon for a neutralino executable just fine. Combine it with `execa` and you can automate it as well.

**Comment by Eliastik** [comment]
> https://www.npmjs.com/package/resedit-cli adds an icon for a neutralino executable just fine. Combine it with `execa` and you can automate it as well.

This doesn't work well. WIndows Defender detect the resulting executable as a malware (false positive).
