### ISSUE TITLE
is there any way we can integrate Robot.js ?

### ISSUE THREAD

**Issue by ShivamJoker** [neutralinojs/neutralinojs#224]
I found this framework very nice but is there any way we can integrate Robot.js library which can control our keyboard and mouse. It's also written in C++

**Comment by shalithasuranga** [comment]
Hey.. We cannot integrate Robot.js directly because there is no Node runtime in Neutralinojs. We are trying to add an extension system. So we can write some native code soon. We are not able to include mouse and keyboard handling directly to the API since the requirement doesn't relate to a general use case. We will update soon about this mouse and keyboard controlling in https://github.com/neutralinojs/neutralinojs/issues/502 Thanks for reporting this one

**Comment by shalithasuranga** [comment]
Hey.. I am closing this because this can be done with a Neutralinojs extension (can be written with any language). Please check https://github.com/neutralinojs/neutralinojs/tree/main/bin/extensions/sampleextension for an example. Thanks for reporting the issue
