### ISSUE TITLE
core-linux and core-macos fork sources are GPL-3.0 licensed.

### ISSUE THREAD

**Issue by ghost** [neutralinojs/neutralinojs#226]
As far as I know, you ***can't re-license*** the core-linux and core-macos codebases (even if it got modified as long as you are using some of the original code) into ***MIT***. I don't see any credits to the original author except for the link below. 
[Original repository](https://github.com/yibo141/Servant)

> referenced in here https://github.com/neutralinojs/neutralinojs/tree/master/core-linux#neutralino-server-for-linux

**Comment by shalithasuranga** [comment]
@momozor  Thanks for pointing out. we will more about the licenses you mentioned

**Comment by momozor** [comment]
:smile: I'm not a lawyer though. I could be totally wrong, but thank you for acknowledging this. :)

**Comment by shalithasuranga** [comment]
Hey.. I am closing this since now the original code of the server has been modified so much and also we are giving credits for the original project in the README

**Comment by shalithasuranga** [comment]
https://github.com/neutralinojs/neutralinojs/tree/master/core-linux
https://github.com/neutralinojs/neutralinojs/tree/master/core-macos

**Comment by Beanow** [comment]
Hello there!

Hope you don't mind me reviving an old issue here, but I believe @momozor makes a good point.
To me it looks like this could be a serious issue.

First two disclaimers:
- This is not legal advice. Best ask your own lawyer.
- Full disclosure, I've donated and contributed to Tauri. Which is an alternative to Neutralino.

Of course I'm assuming this is unintentional, so I'm just hoping to share some insight.

But I think it could be major. That is to say, possibly illegal. Neutralino (including contributors) might have, unintentional or not, pirated their software and might worst case be sued, receive takedowns, etc.

## Background

It's important to understand there is a difference between holding copyrights and being granted a license.

The copyright holder (original author) can do pretty much whatever they like with their code and is automatically protected by copyright law. They can do things such as (re)licensing it, giving ("assigning") the copyrights to someone else, sell, distribute, modify, etc.

It seems the copyright holder here is `Broglie "yibo141"`. They did grant a license for it, namely GPL3. Anyone else (users, contributors, forks, modifications, etc.) needs to abide by the rules of whatever license they're granted (plus general copyright law).

So my analysis here would be there's at least 3 major problems.

## 1. Wrong copyright notice

The original copyright headers look like:

```
/*
 * Author: Broglie 
 * E-mail: <withheld>
 */
```

Which Neutralino changed to:

```
# Copyright (c) 2018 Neutralinojs
```

This seems like an incorrect claim.

To be the copyright owner, Neutralino would need a _legal document_ stating "Broglie" assigns the copyrights to "Neutralinojs". (Simply put, "written permission" from "Broglie".) A GPL3 license doesn't affect the original copyrights, so this would need to be a separate document.

## 2. Relicensing without permission

Changing the license from GPL3 to MIT is not allowed based on the GPL3 license.
The license **can** be changed if you own the copyrights.

So unless "Broglie" grants an MIT license, or assigns copyrights to "Neutralinojs", you cannot change it.
Doing so, I believe would be illegal (copyright infringement).

## 3. Publishing modifications under the wrong license

> Hey.. I am closing this since now the original code of the server has been modified so much and also we are giving credits for the original project in the README

I don't think that's how it works, and actually makes it worse not better :sweat_smile:.

The reason you're allowed to publish modifications at all is thanks to the GPL3 license (not because you hold the copyrights).
But the GPL3 has some conditions, including (my words, not a quote): you can modify it **under the same license** and **with proper copyright notice**, among other conditions.

So every change that was wrongly published with an MIT license and the wrong copyright notice, would violate these conditions.
Meaning those changes were not allowed to be published that way at all, and would also be copyright infringements.

Making a lot of changes, doesn't somehow make it "more MIT" or "more our property".
"Credits" also don't make a difference here. Other than the required copyright notice.

## Suggestions

(Again not legal advice)

I think it would be wise to consult a lawyer. Because it seems like not just the maintainer, but all contributors could be in legal trouble over this. And even with the nuclear option (removing everything related to the fork and starting from scratch), the possibly problematic versions have been published on the internet. Especially because Neutralino also accepts donations, this could be rather problematic and have a real impact on the project.

Finally, I think it would be the right thing to do (as fellow devs) to reach out to the original author. The "strong copyleft" GPL3 and "permissive" MIT license are not similar in spirit. Arguably this change is not respectful of their intentions.

Using their software, not respecting their license choice, while taking donations... getting in touch with them to explain the incident and finding a peaceful solution seems like a good idea to me. Maybe they don't even mind granting the MIT license, that would solve a lot of this (excluding the wrong copyright notice).

Though not a lawyer, if there's more licensing / FOSS topics I could help you out with, do let me know!
It's something I've talked a fair bit about before as part of https://sfosc.org/.

**Comment by shalithasuranga** [comment]
Thanks for pointing out this again with a nice detailed explanation. Since the project has more views now, I think we don't need to keep licencing issues. I will definitely look into this further and do necessary stuff. maybe keeping the original header. licensing headers were added without a further study seems.

I will definitely do what is needed and close this issue with a clear answer.

**Comment by Beanow** [comment]
Glad it was helpful :]
Again if there's more I can do, let me know.

**Comment by shalithasuranga** [comment]
Thanks all again for pointing out this. Now I think everything is fine. I did these updates.

- Reverted the modified GPL licensed code's header to the original one everywhere.
- Added all licenses to https://github.com/neutralinojs/neutralinojs/blob/master/LICENSE
- Added a summary of copyrights and licenses to https://github.com/neutralinojs/neutralinojs/blob/master/README.md#licenses-and-copyrights

I think now it's safe to close this issue. Appreciate your feedback!

**Comment by nothingismagick** [comment]
Awesome, but there is still something lingering, and that is that you are redistributing GPL-3 licensed code. GPL-3 has a sort of "spiderplant" nature to it, which means that if you include any components licensed as GPL-3, you are required to ship the entirety of your project with that license. (This is not the same as LGPL, for example...)

You are of course allowed to license individual code components however you want, but the consumer of **neutralinojs** will with 100% certainty be required to accept the GPL-3 license for the entirety of their derivative work.

My estimation would lead me to believe that the **neutralinojs** codebase has to be declared as GPL-3 because of the requirements of redistributing that one bit of GPL-3 source code. If this is what you want, then this is a good thing and a great decision for the entire FLOSS community. This would, however, have implications for anyone wanting to use this library in their proprietary projects...

**Comment by shalithasuranga** [comment]
Thanks for the feedback regarding the updates. Hm yeah. I just went a bit deeper into GPL-v3 docs. As you mentioned, looks like we have to use GPL-v3 because integrated a component that uses GPL-v3. As I understood, 

- Using `Neutralinojs core: GPL-3.0` instead of `Neutralinojs core: MIT` in README
- Doing the same thing in the LICENSE file.

will conclude the licensing problem. Looks good? @nothingismagick

**Comment by nothingismagick** [comment]
That is exactly what I would recommend.

**Comment by shalithasuranga** [comment]
I've updated like that. Thank you very much for the support and guidance.

**Comment by Beanow** [comment]
> GPL-3 has a sort of "spiderplant" nature to it,

That seems right to me. So using this dependency would require the project uses GPL3 as well.

A few points I would add:
- Switching license for the project is a **big deal**. I'd highly encourage talking to your contributors and userbase to see if GPL3 also works for them before committing to it. It may be worth considering changing to a different dependency if GPL3 is not a good fit for Neutralino.
- Everyone who has contributed to the project (as they're copyright holders for those contributions) needs to formally grant the new license. The same notion I explained about relicensing the original, applies to the modifications too.
  (So that would be Neutralinojs core and HTTP server on Linux and macOS contributors.)
-  Older versions, including commits, from the fork until the license fixes might still be in a troubled legal state. So I think it's worth thinking about how to handle those as well. I can't tell you what a good solution would be here, but things to consider are: protecting your users from accidentally using it, and what an acceptable solution is for "Broglie".
- For the copyright statement, I believe who modified it may need to be added to the copyright header/files as a list.
  So I think the server would be Broglie & Neutralino (and contributors).

**Comment by shalithasuranga** [comment]
Thanks, @Beanow  for the feedback. Yeah, I will discuss this licensing change in our Slack chat and let everyone know. We would like to keep the server's code as it is with the original author's credits. I really appreciate it if you have some time to make a pull request with your suggestions. I didn't clearly understand the required changes from your suggestions.

**Comment by Beanow** [comment]
@shalithasuranga right now it's probably early for a PR because of open questions. Is GPL3 acceptable for you, what is discussed with Broglie, etc.

But I would encourage asking a lawyer for legal advice, it would be unwise for me to create the PR.

But I can try to clarify my thoughts.
> We would like to keep the server's code as it is with the original author's credits.

I think, to include the GPL3 server, it's required to switch the core to GPL3 as well like you did. But this needs permission from **all neutralino contributors**. Because they originally submitted MIT code, and they retain the copyright for their contributions. Only they can switch it to GPL3.

This written permission is a legal document, so again I'd ask a lawyer for specifics.

Finally the copyright notice, put simply 'should include everyone'. So "© original author" is missing the later contributions, and "© Neutralino" is missing the original author. I think it should somehow include both of them.

**Comment by shalithasuranga** [comment]
Hello everyone, thanks for the guidance and support. As @Beanow explained, re-licensing should respect the contributors' response and feedback. I took a fast decision to switch to GPLv3 because there were some legal issues.

Good news for all of you and the community.  Now, the project no longer uses GPL licensed code. I replaced all of them with MIT licensed library and re-implemented necessary code myself. So now Neutralinojs happily used MIT. Moreover, I also used copyright text as "Neutralinojs and contributors"

Thanks, everyone again. for your support.
