### ISSUE TITLE
current kernel API model is harmful?

### ISSUE THREAD

**Issue by ghost** [neutralinojs/neutralinojs#235]
Hi.

I'm not 100% sure about this..but isn't it dangerous to expose system calls via the API from a server? What if a client accidentally visited a website that will cause the Neutralino to execute dangerous api calls (like os.run, filesystem access etc)???

**Specifications**  
* NeutralinoJs Version: 1.3.0
* Platform: Linux, Windows, MacOS

**Comment by apollolux** [comment]
I share these concerns to a much lesser degree for two main reasons:

* to me it seems about equally as likely that a randomly acquired Neutralino-based app would perform malicious activity or perceived as doing such vs a randomly acquired fully native program, or somewhat less likely that a Neutralino one would or even could be as malicious;
* to me it does not seem likely that a malicious website would or even could interact with a running Neutralino-based app unless it somehow knew its port number and/or the site was loaded within the app somehow (e.g. a browser app)

Many app frameworks (Node with or without Electron or NWjs, Deno, etc) as well as an OS's own APIs expose ways of running processes on the host, where Deno seems to be the only one so far of those I listed that has the extra, finer-grained explicit feature sandboxing built into it.

**Comment by momozor** [comment]
I see. Thank you. The sandboxing sounds like a good idea too.

**Comment by shalithasuranga** [comment]
Hey.. Thank you very much for discussing this. I am closing this issue since:

- Now we have a security model for NL_TOKEN. Please check more details from [here](https://github.com/neutralinojs/neutralinojs/blob/main/CHANGELOG.md#core-auth)
- Browser CORS checks typically block if someone tries to access the Neutralino WebSocket port from a remote script.
- Developer can control native API permissions via `nativeBlocklist` or `nativeAllowlist`
