### ISSUE TITLE
Does Neutralinojs use the default browser?

### ISSUE THREAD

**Issue by tiredoftry** [neutralinojs/neutralinojs#236]
This saves a lot on file size, but it pushes you into browser compatibility issues.

**Comment by momozor** [comment]
Or we could ship webkitgtk2 for all platforms instead of using default browsers. AFAIK, webkitgtk2 is lightweight on memory and small compared to full blown chromium or edge (which based on chromium if I can remember)...

**Comment by ghaspias** [comment]
Is there some reason for Neutralino to be using Internet Explorer instead of Edge (I am running Windows 10)? WebView is supposed to use Edge on Windows (thats what it says on the WebView github page), and in fact WebViewJar (a java wrapper for WebView) uses Edge...
In any case, given the choice between IE11 and WebKitGtk, I will pick the latter anytime...

**Comment by fitzzz** [comment]
yes i am loving neutralinojs and started using it for a project, but once I realized it rendered in IE... well... i'm starting to have second thoughts :-(

**Comment by shalithasuranga** [comment]
Closing this because we use EdgeChromium/HTML on Windows with the latest Neutralinojs version.  Regarding Chromium support, I think then we have to bundle with Chromium source and it makes everything heavy. The electron framework does the same. If someone really needs to build apps with Chrome-only, I would recommend https://github.com/zserge/lorca

Thanks for the ideas!.. Sorry! took a long time to respond.

**Comment by tiredoftry** [comment]
Thanks for the update and glad to see EdgeChromium is being used now.
