### ISSUE TITLE
Opening a file and get full filepath

### ISSUE THREAD

**Issue by patarapolw** [neutralinojs/neutralinojs#267]
It would be nice if this is possible, but it seems to either rely on backend dialog, or use a modified version of web browser, like Electron.

![Screen Shot 2563-05-03 at 19 00 48](https://user-images.githubusercontent.com/21255931/80913652-6e9f2b00-8d70-11ea-8fd9-b9a22e4fd453.png)

I have been using Electron, but I failed to build for Linux with an error. I can multi-platform build for Window and MacOS (on MacOS), though.

**Comment by shalithasuranga** [comment]
Hey.. do you mean the requirement is to select a file and get the full path? If yes https://neutralino.js.org/docs/api/os#osshowdialogopendialogopenoptions can be used. Otherwise, if you mean you need to search the current directory and get a file, you may try https://neutralino.js.org/docs/api/filesystem#filesystemreaddirectoryreadfileoptions
