### ISSUE TITLE
Publish Neutralino client library to NPM

### ISSUE THREAD

**Issue by Saiv46** [neutralinojs/neutralinojs#276]
**Expected Behavior**  
NPM has package `neutralino-client-library` to install
 
**Actual Behavior**  
You need to bundle package by yourself

**Comment by shalithasuranga** [comment]
Hello.. Thanks for suggesting a nice idea.. We thought about this idea earlier too and decided to download the client from the Github repo instead. It is chosen due to the following reasons.

- `neutralino.js` is dynamic. Neutralino server injects some JavaScript into it dynamically.
- All users may not use npm and frontend frameworks to develop Neutralinojs apps.

Right now, the Neutralinojs client will be downloaded/updated with `neu create` and `neu update` commands. Besides, it is git ignored.

Thanks again for the idea.
