### ISSUE TITLE
Neutralino crashed each time if try to load a script outside of /assets

### ISSUE THREAD

**Issue by PhieF** [neutralinojs/neutralinojs#286]
Hi !

First, thanks for your work 

**Expected Behavior**  
  <script src="/libs/jquery.min.js"></script> 
should load javascript file ?
  
**Actual Behavior**  
Neutralino crashed each time if try to load a script outside of /assets
<script src="/libs/jquery.min.js"></script>
will crash  (core dumped)
but
<script src="/assets/jquery.min.js"></script>
seems to work

**Specifications**  
* NeutralinoJs Version: 1.4.0
* NeutralinoJs CLI version: ?
* Platform: Ubuntu 20.04

**Comment by blex41** [comment]
This is expected behavior, as you can see in Neutralino's router: 

https://github.com/neutralinojs/neutralinojs/blob/1c220d0e1c652bfe2fc82144a6f6a8f66a652a3b/core-windows/src/router.cpp#L87-L93

Any request path that does not start with `/assets` and does not fulfill any other route typology will break. The [documentation](https://neutralino.js.org/docs/#/gettingstarted/quickstart?id=neutralino-app-file-structure)  says to put any asset in that `assets` directory. But nothing prevents you from creating a `libs` folder inside of `assets`.

**Comment by shalithasuranga** [comment]
Hey.. usually neutralino needs to see all of the app resources in `assets`. But regarding crashing. need to apply a fix. :) Thanks @blex41 for the reply.

**Comment by shalithasuranga** [comment]
Hey.. now the project structure is flexible and it's like any other static file server: https://neutralino.js.org/docs/developer-environment/project-structure
