### ISSUE TITLE
Need guidance regarding using ExpressJs server in neutralinojs

### ISSUE THREAD

**Issue by JigneshRaval** [neutralinojs/neutralinojs#315]
Hi @shalithasuranga ,

I have just started exploring neutralinojs framework and it looks very promising and I am exited about new futures that @neutralinojs team will implement. I need your guidance for using ExpressJs server for API requests in neutralinojs.

I have created one small SPA using React, node.js and [ExpressJs](https://expressjs.com/) for Blog articles with simple CRUD operations. Which stores/updates and retrieve data in one JSON file using [NeDb](https://github.com/louischatriot/nedb)

Can you please guide that 
1) Is it possible to use ExpressJs in neutralinojs or can i move/port the same code base in this framework?
2) Can we have any option similar to nw.js or electron to provide server.js file in settings.json?
Example : https://docs.nwjs.io/en/latest/References/Manifest%20Format/#main

Your help would be appreciated.

Thanks,
Jignesh Raval

**Comment by shalithasuranga** [comment]
Hey @JigneshRaval  Sorry for taking a long time to respond. Thanks for trying Neutralinojs. Please check the answers for your questions below.

1. You can simply consume your REST API in Neutralinojs but you will not be able to port it quickly because there is no Node runtime behind Neutralinojs. You can simply start your API with `Neutralinojs.os.execCommand` and start using it with browser's `fetch` API.
2. Yeah sure.. Please add your entry URL with `url` property in config.
