### ISSUE TITLE
Need help : Application server is crashing on every few minutes

### ISSUE THREAD

**Issue by JigneshRaval** [neutralinojs/neutralinojs#319]
Hi @team

I need help in following issue.
I am new to NeutralinoJS, and trying to develop simple HTML app having one form in it. I have set browser mode for development. But the server is crashing and stop working on every couple of minutes.

finally I got following error message.
![image](https://user-images.githubusercontent.com/11232532/94843153-ecf41c00-0439-11eb-931e-82c3ff82b5ee.png)

Below is the screenshot of simple app.
![image](https://user-images.githubusercontent.com/11232532/94843566-7efc2480-043a-11eb-9890-0a9af17c144c.png)

Platform : Windows7
```
debug.log file

[1001/224104.802:ERROR:registration_protocol_win.cc(131)] TransactNamedPipe: The pipe has been ended. (0x6D)
[1001/224417.318:ERROR:registration_protocol_win.cc(131)] TransactNamedPipe: The pipe has been ended. (0x6D)
[1001/225131.008:ERROR:registration_protocol_win.cc(131)] TransactNamedPipe: The pipe has been ended. (0x6D)
[1001/225549.920:ERROR:registration_protocol_win.cc(131)] TransactNamedPipe: The pipe has been ended. (0x6D)
```
Please guide on this.

Thanks,
Jignesh Raval

**Specifications**  
* NeutralinoJs Version: [1.5]
* NeutralinoJs CLI version: [1.7.0]
* Platform: [window7 64bit]

**Comment by JigneshRaval** [comment]
Hi team,

I tried by removing all the newly added code and then added code back one by one and now it is working fine, but sometimes still server is breaking and doesn't provide any proper log. 

**Also observed following things while using CLI :**
After running `neu run` command If we press `Ctrl + C` to stop server, but it doesn't stop server and it runs continuously until it break itself due to any error.

But now it is working almost fine.

Below is what I have developed today using NeutralinoJs + Bootstrap:

![app-dashboard-slideout-form-02-Oct-2020](https://user-images.githubusercontent.com/11232532/94955110-b5ec3c00-0507-11eb-83ea-a498220a96c2.png)

Here is my repository URL if any one is interested to look into and can suggest better development approach using NeutralinoJs.

https://github.com/JigneshRaval/neutralinojs-app

Thanks,
Jignesh Raval

**Comment by shalithasuranga** [comment]
Hey.. Thanks for letting us know about your app and ideas. Very nice and useful app. btw. Do you mean "neutralino" process will be disappeared from the task manager suddenly while you are testing your app? If yes I think you need to use window mode because this desktop mode is only for debugging and there could be some issues with ping in desktop mode (In each n seconds Neutralino client will send a ping request to server to keep active).
Maybe using port as 0 looks good because it uses a random available port. Also you will be able to use React template with your next projects.

**Comment by JigneshRaval** [comment]
Hi @shalithasuranga

Thank you very much for your reply.

I am new to Neutralinojs and trying to explore and learn it's features. I have also tried Electron and NW.js in the past but Neutralinojs seems promising app due to it's lightweight and simple architecture.

I want to add some feature requests. Can you please guide that how can I add that?

Thanks,
Jignesh

**Comment by shalithasuranga** [comment]
Thanks for reporting this issue. We need to add support for older versions of Windows. I will close this since there is a specific issue to track it #486 

Regarding your other questions, 

1.  I think that's an issue with IE webview. Right now we use Edge webview so it will work.
2. This is also related to the IE instance seems. I think you can try once we add support for older Windows versions.
