### ISSUE TITLE
get data in variable

### ISSUE THREAD

**Issue by anteolic** [neutralinojs/neutralinojs#335]
How to get data in variable outside of this function??? i always get nothing cause function is asynchronous. 

```
let mydata;

// The stored data is being retrieved from the JSON based data store. 
Neutralino.storage.getData('test',
// executes when data is successfully retrieved.
    function(content) {
    console.log('The data you requested for \n');

    // the data that has been retrieved.
    console.log(content);
   mydata=content;

    },
// executes if an error occurs
   function () {
    console.log('An error occured while retrieving the data.');

    }
);

console.log(mydata);

```

**Comment by shalithasuranga** [comment]
Hey...You can use await and Promises easily to get the value out side of the function but the issue is that ie11 is not supporting those features (Neutralinojs uses ie11 component on Windows). I suggest if you plan to make your app for Windows users too you can write your logic inside the callback function or by calling another method.

If you plan to make your app only for Linux and Mac you can wrap this code with a promise and you can use await to make the function synchronous. For example let mydata = await getData();
