### ISSUE TITLE
JS error "Object does not support property or method 'from'"

### ISSUE THREAD

**Issue by BenStigsen** [neutralinojs/neutralinojs#341]
**Expected Behavior**  
It should load https://meditofoundation.org/meditations without problem,
  
**Actual Behavior**  
It opens https://meditofoundation.org/meditations and shows the following error:
![image](https://user-images.githubusercontent.com/24865450/102295729-4d302f80-3f4c-11eb-9b99-112624a2b402.png)

**Steps to Reproduce the Problem**  
1) **app.js**:
 ```js
Neutralino.init({
    load: function() {
        window.location.href = "https://meditofoundation.org/meditations";
    },
    pingSuccessCallback : function() {

    },
    pingFailCallback : function() {

    }
});
```
2) Start the application

**Specifications**  
* NeutralinoJs Version: 1.6.0v
* Platform: Windows 10 19041

**Comment by apollolux** [comment]
`Object.from` is ES6. Neutralino on Windows still uses MSHTML under the hood rather than EdgeHTML or WebView2, so is limited to ES5. If you want ES6 while waiting for Neutralino to update to use newer JS engines you'll need to run an ES6 shim before loading the webpage, and even then you'll probably want to load the page in an iframe instead of a full-on window location change to have a better chance of your start page's code being available to use.

**Comment by shalithasuranga** [comment]
Please try the latest version. Now Neutralinojs use Edge on Windows.
