### ISSUE TITLE
neu.res is missing problem

### ISSUE THREAD

**Issue by ovresko** [neutralinojs/neutralinojs#383]
**Expected Behavior**  
Run fresh app  
**Actual Behavior**  
Error neu.res is missing error
ERROR [src/resources.cpp:makeFileTree] resources::makeFileTree error: res.neu is missing.
gspro was terminated.

**Steps to Reproduce the Problem**  
- win 10 fresh build default template

**Specifications**  
* NeutralinoJs Version: 1.8
* NeutralinoJs CLI version: 2.3.3
* Platform: Win 10

**Comment by shalithasuranga** [comment]
Hey.. Could you let me know how did you launch the app?

**Comment by ovresko** [comment]
neu run from app folder

**Comment by aakashsinghbais** [comment]
The same ERROR shows on Ubuntu 20.10, though the app runs when run using the `neu run` command via terminal (error still persists and is shown in terminal).

**Comment by shalithasuranga** [comment]
Yeah exactly, the app is running but the error is shown. It is fixed with the next release. But not sure why @ovresko 's app is not working..

**Comment by Thomasorus** [comment]
Same problem here. 

Fresh install of neutralino on the last ubuntu, followed instructions for the hello world app. Works when using `neu run` but not after build for the linux build.

console output:

```
ERROR [src/resources.cpp:makeFileTree] resources::makeFileTree error: res.neu is missing.
ERROR [src/settings.cpp:getSettings] std::exception
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be string, but is null
Abandon (core dumped)
```

**Comment by acidtumbleweed** [comment]
Also running into this issue on a fresh Windows 10 install + fresh neu install, please advise - the application window appears but I can't tell if this is causing any other underlying issues at runtime?

**Comment by shalithasuranga** [comment]
Hey.. I checked `neu run` and `neu release` on Linux.. worked fine with the latest release. But there was an issue on Windows.. Looks like working fine now.

**Comment by Thomasorus** [comment]
Ok I finally understand what's going on and why maybe @ovresko had the same problem. 

Tom sum it up:
- `neu create` worked fined
- `neu run` also worked
- `neu build` returned a success message but no dist folder or anything that you can notice on first sight

So I thought it was rebuilding the myApp-linux file at the root of the folder and that it was the built program. That's what I was trying to execute.

Using the `neu release` (first time I'm seeing this command since I did not go inside the neutralinojs-cli repo) command created the dist folder with the working versions inside.

So if that's the same for everyone I would recommend:
- Being more clear about what the `build` command do
- Copy and explain the neutralino-cli commands inside the main neutralinojs Readme/Doc.

Thanks for taking the time to help @shalithasuranga.

**Comment by shalithasuranga** [comment]
Hey Thanks for ideas. I agree . the documentation is not having all the things clearly. I will look into docs. Also please notice that we are planning for v2.0.0 release asap.     We can expect very much enhanced version.

**Comment by shalithasuranga** [comment]
Please check the latest version: https://neutralino.js.org/.. Closing the issue since we have no issue with `neu run` in v2
