### ISSUE TITLE
Support for Android and iOS

### ISSUE THREAD

**Issue by ibrahemesam** [neutralinojs/neutralinojs#384]

**Comment by alixsep** [comment]
if this actually happens, neutralino will become a game changer. would be so glad, please make this happen! 🥺❤

**Comment by shalithasuranga** [comment]
Hello.. thanks all for discussing this issue. Please consider Neutralinojs as a "desktop application development" framework (As the project title says) like Electron. We will not extend the official implementation for mobile platforms but love to see some forks in the future.
We can somehow add support for mobile platforms but then the project's architecture will become messy. But, as mentioned, interesting to see if someone experiments with a fork.

Very interesting thread to check: https://github.com/electron/electron/issues/562

**Comment by jquindlen** [comment]
> Hello.. thanks all for discussing this issue. Please consider Neutralinojs as a "desktop application development" framework (As the project title says) like Electron. We will not extend the official implementation for mobile platforms but love to see some forks in the future. We can somehow add support for mobile platforms but then the project's architecture will become messy. But, as mentioned, interesting to see if someone experiments with a fork.
> 
> Very interesting thread to check: [electron/electron#562](https://github.com/electron/electron/issues/562)

I am intending to make my neutralino app have an Android port in the near future and from past experience manually porting web apps to Android, I think this will be rather easy to do.

My open source app uses a small subset of neutralino's available methods, so I do not intend to fork neutralino but instead to make an open source Android WebView wrapper app that provides a barebones implementation of neutralino.  

Instead of porting any neutralino code, I will instead create a custom fake neutralinojs file that provides just the neutralino namespace, classes, and methods my app uses but with my own javascript code that provides the same input/output and communicates with the wrapper to allow the native OS interactions required.  

The first draft at this I won't even try to use the res.neu but instead I'll use the base resources such as the images, stylesheets, html, javascript files, etc.

I'm pretty confident this approach will work because before electron and neutralino I used to manually make wrappers on each platform (Windows, Mac, Linux, Android.)  Awesome tools like neutralino have eliminated most of the cruft I used to deal with in shipping HTML and Javascript based apps, so I don't mind rolling my own for Android.

I've made a few Android WebView wrapping apps in the past so this is a big reason why I'm going this route. Only difference for me this time is that I'll be mimicking neutralino so that I don't need to rewrite any code from the desktop versions of my neutralino app.

I'll tag this issue in my tracker so that I can post an update here when I've uploaded the code to the repo for my Android wrapper.  I think December 14th, 2021 is the deadline, so I should have this working soon hopefully.  I'll be sure to clearly document in the repo and code comments that this code is NOT neutralino and point to this repo to clear up any confused googlers in the future.

**Comment by tellts** [comment]
Hello, Jquindlen. How is development progressing?

**Comment by cquasar** [comment]
> > Hello.. thanks all for discussing this issue. Please consider Neutralinojs as a "desktop application development" framework (As the project title says) like Electron. We will not extend the official implementation for mobile platforms but love to see some forks in the future. We can somehow add support for mobile platforms but then the project's architecture will become messy. But, as mentioned, interesting to see if someone experiments with a fork.
> > Very interesting thread to check: [electron/electron#562](https://github.com/electron/electron/issues/562)
> 
> I am intending to make my neutralino app have an Android port in the near future and from past experience manually porting web apps to Android, I think this will be rather easy to do.
> 
> My open source app uses a small subset of neutralino's available methods, so I do not intend to fork neutralino but instead to make an open source Android WebView wrapper app that provides a barebones implementation of neutralino.
> 
> Instead of porting any neutralino code, I will instead create a custom fake neutralinojs file that provides just the neutralino namespace, classes, and methods my app uses but with my own javascript code that provides the same input/output and communicates with the wrapper to allow the native OS interactions required.
> 
> The first draft at this I won't even try to use the res.neu but instead I'll use the base resources such as the images, stylesheets, html, javascript files, etc.
> 
> I'm pretty confident this approach will work because before electron and neutralino I used to manually make wrappers on each platform (Windows, Mac, Linux, Android.) Awesome tools like neutralino have eliminated most of the cruft I used to deal with in shipping HTML and Javascript based apps, so I don't mind rolling my own for Android.
> 
> I've made a few Android WebView wrapping apps in the past so this is a big reason why I'm going this route. Only difference for me this time is that I'll be mimicking neutralino so that I don't need to rewrite any code from the desktop versions of my neutralino app.
> 
> I'll tag this issue in my tracker so that I can post an update here when I've uploaded the code to the repo for my Android wrapper. I think December 14th, 2021 is the deadline, so I should have this working soon hopefully. I'll be sure to clearly document in the repo and code comments that this code is NOT neutralino and point to this repo to clear up any confused googlers in the future.

Any updates on this?

**Comment by timmypidashev** [comment]
Would love to see this, tauri is great but for my purposes is a little bit too much overhead for my web projects. Neutrolinojs adding mobile framework support would be awesome. I am not experienced enough in the framework to do this yet but, the thought is definitely staying in the back of my mind.
