### ISSUE TITLE
Support for .NET 5/6

### ISSUE THREAD

**Issue by HeroinGyrl** [neutralinojs/neutralinojs#448]
Will neutralino support .NET like [Electron.NET](https://github.com/ElectronNET/Electron.NET) does?

**Comment by danisss9** [comment]
Right now i dont think there is oficial support. But you can do it manually by shipping a asp.net web server alongside your app.

**Comment by shalithasuranga** [comment]
The upcoming release (v4) can be used with any backend language via extensions API/child process API. Therefore, I am closing the issue. Please check the documentation when v4 is released ;)

**Comment by HeroinGyrl** [comment]
> The upcoming release (v4) can be used with any backend language via extensions API/child process API. Therefore, I am closing the issue. Please check the documentation when v4 is released ;)

hey @shalithasuranga do you mean with extensions API that it will be also possible with Blazor?

**Comment by shalithasuranga** [comment]
Hey.. Here is the general idea behind extensions API. Neutralino process lists to a WebSocket port to respond to native calls. So, we built an extensions system based on it. Now we can access both app instance and native API via another process. So if you write a process with any language, you can connect with the app/process via WebSocket as an IPC. I am not sure how we can integrate Neutralinojs with Blazor since both are different cross-platform development environments. However, you can integrate Neutralinojs with C# with WebSocket IPC
