### ISSUE TITLE
Blank screen on other devices.

### ISSUE THREAD

**Issue by Babyyoda777** [neutralinojs/neutralinojs#473]
**Expected Behavior**  
App should work normally on end users' devices and display something
**Actual Behavior**  
App on user end is blank

**Steps to Reproduce the Problem**  
 1. Make app
 2. Sen to user pc
 3. Open app

**Specifications**  
* NeutralinoJs Version: [Version number of NeutralinoJs framework] latest
* NeutralinoJs CLI version: [neu-cli version] latest
* Platform: [Platform specifications] windows 10 20h2

**Comment by JoaquinDecima** [comment]
Hello, I am not a creator, but could you provide the app for me to review it, I did not get this problem and I can not replicate it either.

I'm just helping with the Issues

**Comment by hypherionmc** [comment]
Did you try this?
![image](https://user-images.githubusercontent.com/63595580/121166855-b6389600-c851-11eb-938e-6b4dcfa9d7e5.png)

**Comment by shalithasuranga** [comment]
Thanks for answering @JoaquinDecima and @hypherionmc . Yes, there is a technical limitation. As explained in [here](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app#step-1-creating-a-new-app) we need to configure UWP to load `localhost` URLs. I'm not sure this situation will be changed with the latest windows updates. 

If you are making a setup file for Windows users you could run this command automatically with the user's consent. I will close this issue since this is a well-known problem. 

We will keep https://github.com/neutralinojs/neutralinojs/issues/465 open

**Comment by MyBlood** [comment]
> As explained in [here](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app#step-1-creating-a-new-app) we need to

I have done this, but the window still remains blank.
![image](https://user-images.githubusercontent.com/20350848/124993586-3a4a8d00-e04d-11eb-8d03-c0f9c0cbc597.png)
![image](https://user-images.githubusercontent.com/20350848/124993646-52baa780-e04d-11eb-99d2-1b0b3de90950.png)
