### ISSUE TITLE
Use with an express server

### ISSUE THREAD

**Issue by wtesler** [neutralinojs/neutralinojs#501]
I might be misunderstanding what this library is about, but how would I go about running an express server in the background while the app is running? I actually don't even see a package.json in the sample project. How do I import npm modules?

**Comment by iitsuraj** [comment]
Hey, You able to start an express server

**Comment by Blatman** [comment]
FWIW I have found I can run an Express server OK via the os.execCommand() API - it involves running the node module as a packaged executable.

express is a packaged executable using pkg which is a node module that will bundle Node with the required node modules.

document.getElementById('startExpress').onclick = async function startExpress(){
    let response = await Neutralino.os.execCommand({
//        command: 'ls'
        command: window.NL_PATH + '/./express'
    });

Note: In order to stop the express process after the Neu app closes the PID needs to be found -

document.getElementById('stopExpress').onclick = async function stopExpress(){
    let checkPid = Neutralino.os.execCommand({
        command: 'lsof -t -i tcp:5000'  // -t is Terse result giving PID of Express server only
    }).then(function(checkPid) {
        var servPid = checkPid.output
        Neutralino.os.execCommand({
            command: 'kill -9 ' + servPid
        });
    });
}

The above code is also used in the main.js file for the exit functions so the process is not left running after the app closes.

The attached files indicate typical usage - the index.js file is used by the pkg bundling and the other two will reside in the neutralino app bundle.

[Archive.zip](https://github.com/neutralinojs/neutralinojs/files/7177034/Archive.zip)

**Comment by wtesler** [comment]
Thanks! I ended up going with Electron which has a Main/Renderer thread concept, but I might come back to this at some point.
