### ISSUE TITLE
API method to create / destroy WebView windows dynamically

### ISSUE THREAD

**Issue by tinomatic** [neutralinojs/neutralinojs#510]
**Expected Behavior**  
API to include methods to create/destroy one or more WebViews programatically with params such as height, width, resizable, decoration, url (content source), etc.
  
**Actual Behavior**  
Currently the framework seems to offer a single WebView with content effectively defined at initiation, as far as I can tell from the docs. Please correct me if i'm wrong ;)

**Specifications**  
* NeutralinoJs Version: 2.4.0

**Comment by shalithasuranga** [comment]
Hey.. The neutralino is designed in that way because we don't use Node to run as the main process.  Neutralinojs has a once process to take care of the webview, and loaded-Js scripts will communicate with the main process to do native operations. However, we can add multiple windows support which you need to have. We can spawn a Neutralino process per window to implement multi-window support.

Now I will close this issue because we already have a feature request (https://github.com/neutralinojs/neutralinojs/issues/249) to track the multi-window support.

Thanks for reporting the issue.
