### ISSUE TITLE
Try to add chrome as a Neutralino mode

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs#517]
Looks like we can disable tabs, extensions, etc with args in chrome binary.

**Comment by Blatman** [comment]
@shalithasuranga  - Just wondering whether this would be a good idea as an option to Safari since Safari seems to be lagging on some fronts.
I'm finding that the media file playbacks using HTML tags are not working (since 3.0.0) whereas all other browsers are fine if browsing to the server port of the main app window. Also the draggable is broken with Safari but again works OK with other browsers on the server port. Also .ogg/.ogv is not supported by Safari but is with other browsers. Chrome also has a huge number of cli switches which may be useful. Even if it is not already installed on a Mac it is not difficult to  install and it is not as if it has to be bundled with every app. More like a VB runtime really - once installed that's it.

**Comment by shalithasuranga** [comment]
Hey.. @Blatman Yeah, thanks for info.. Now this Chrome mode will work on Linux and macOS.. Need to test on Window
