### ISSUE TITLE
neutralino-win.exe detected as virus (false positive) 

### ISSUE THREAD

**Issue by siquylee** [neutralinojs/neutralinojs#554]
Windows Security detects neutralino-win.exe as PUA:Win64/CoinMiner.J!ibt virus. I think this is false positive. Do you have any solution for this?

**Comment by hypherionmc** [comment]
This relates to my issue from a while ago. I didn't get this issue again after I compiled it myself

**Comment by shalithasuranga** [comment]
Hm yeah I guess this is because the pre-compiled binary is missing developer details, version info in manifest. I checked Electron. They add those details to the pre-compiled binary. So for now. I will update the pre-compiled binary with the Resource hacker. Ideally, I think we need to change the manifest/icon with the neu CLI.

**Comment by shalithasuranga** [comment]
Hello.. Could you all please run `neu update` and check. I've updated the binary's manifest, etc with the [Resource hacker](http://www.angusj.com/resourcehacker/)

**Comment by siquylee** [comment]
Microsoft Defender still sees it as virus but I think it's good, check the scan report https://r.virscan.org/language/en/report/36314a868d6e2e29c4148d53ff1e2327

**Comment by shalithasuranga** [comment]
Thanks for checking @siquylee. Looks like we can close the issue since now only very very few virus guards make false positive detections. I also did some tests with web scanners. Let's close this one and check again if someone has an issue with a specific virus guard and Neutralino windows binary.
