### ISSUE TITLE
Is it still possible to use typescript?

### ISSUE THREAD

**Issue by wliumelb** [neutralinojs/neutralinojs#570]
Thank you for creating this awesome project.

The typescript template is labelled as archived and I could not find any mentioning of typescript in the documentation. Is typescript still supported in v2?

**Comment by AntonWedemeier** [comment]
I am building my (hobby) application in typescript. That poses no problem. Only the translation requires an extra step, which I automated with a bat.file (on windows).
I also made a neutralino.d.ts file, as best I can from the documentation. Perhaps you want me to share it with you.

**Comment by shalithasuranga** [comment]
Hey.. @wliumelb, we can build any frontend framework and also TypeScript to build Neutralinojs apps. Neutralinojs has a built-in static file server. Therefore, you just need to place transpiled source files with HTML inside the original resource's path. I think you can check this tutorial https://www.youtube.com/watch?v=TreJXBarK6k for more information. It explains how to make Angular-based Neutralino apps.

I'm closing this issue since it is already answered ;)
