### ISSUE TITLE
Whitescreen issue on Windows even after running command

### ISSUE THREAD

**Issue by hypherionmc** [neutralinojs/neutralinojs#578]
**Expected Behavior**  
When running the app on windows, I expect it to work as intended, showing the contents of the app in the window

**Actual Behavior**  
The app show up with a white screen only on some windows machines, even after running the command given in the docs. I haven't been able to replicate this myself and I'm not sure what causes it

User confirms they have MSEdge installed with the latest updates and they did execute the command

**Specifications**  
* NeutralinoJs Version: 2.6.0
* NeutralinoJs CLI version: 5.3.1
* Platform: Windows 10 Pro 64 as far as I can tell

**Comment by maxruby** [comment]
I suspect it is related to the same issue I am having on Windows and reported here:
https://github.com/neutralinojs/neutralinojs/issues/399#issuecomment-908651277

**Comment by Dechowmedia** [comment]
> I suspect it is related to the same issue I am having on Windows and reported here:
> [#399 (comment)](https://github.com/neutralinojs/neutralinojs/issues/399#issuecomment-908651277)

Hi,

I ran into a similar issue where the whitescreen appeared.
In my case this was due to running an Create React App application - without specifying the "homepage" key value pair in the package.json

However after specifying "/resources/" it went smooth:
`"homepage": "/resources/",`

If you are not running Create React App - You may want to inspect the network requests to see if your files are actually fetched.
You may receive a 200 OK but the file's content being empty (because they don't exist on the address but the server  responds by standard 200 to everything even missing files)

Just some pointers.

**Comment by rince1984** [comment]
As in other issues mentioned it might help to run cmd as admin to execute the command from the documentation (CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy").

I made a little tool with neutralinojs for our customers and have created an installer via inno setup (a free tool to create installers) to install the tool on customers pc. Within the installer I call the command (CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"). Because the installer itself needs admin rights the command will be executed properly.

**Comment by hypherionmc** [comment]
And as I mentioned in my initial report, the command was executed and didn't fix ANYTHING! I also came across this personally and it comes down the the webview runtime failing to load, and neutralinojs doesn't realize this and then just keeps showing the white screen, instead of crashing

**Comment by gitthangbaby** [comment]
Is it possible to skip this completely. That way apps could be distributed without elevation, fantastic.

**Comment by shalithasuranga** [comment]
This issue can be solved by installing the WebView2 runtime which is needed for most hybrid apps. Thanks :tada: However, we would love to research more about possibility of getting rid of this admin command :)
