### ISSUE TITLE
Invoke function of neutralino.js client from remote page doesn't have any response (neutralinojs 2.0)

### ISSUE THREAD

**Issue by kiett** [neutralinojs/neutralinojs#585]
We use neutralino.js to open a remote page by point the **url** attribute from neutralino.config.json to our page and also set "enableNativeAPI": true

Our index.html of the remote page:

`<!doctype html>
<html lang="en">
    <head>
        <title>The Remote Page</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
    </head>
    <body>
        <div id="root"></div>
        <script type="text/javascript" src="neutralino.js"></script>
        <script>
            Neutralino.init();
            Neutralino.window.setTitle('This is neutralinojs');
        </script>
    </body>
</html>`

The neutralinojs object is available, but invoking its methods would not do anything.
Does anyone have the same issue? Please help!!! Appreciated.

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting this..  Please note that, native API is disabled (`window.Neutralino` no longer exists) for remote pages due to security problems.  Note that Neutralinojs can use used to build apps with local resources, but we can check if there is a solution to enable `window.Neutralino` with strict security in the future. For now, I will close this one, but we will add this to our roadmap if there is a possible approach to solve this :)
