### ISSUE TITLE
Single binary

### ISSUE THREAD

**Issue by caramboleyo** [neutralinojs/neutralinojs#592]
When I do `neu build -r` i get a binary that does not run without the res.neu file in the same folder. Is it possible to have everything in one file?

**Comment by shalithasuranga** [comment]
Hey.. Thanks for reporting this issue/idea. We would like to have `res.neu` with binary for several reasons such as easy-update, simple resource loading, easy resource switching (one binary to run multiple apps), etc. For now, I will close this one since Neutralino's design doesn't support a single binary. But, let's look back to this someday when more developers point out this feature.
