### ISSUE TITLE
Unsupported file extension

### ISSUE THREAD

**Issue by caramboleyo** [neutralinojs/neutralinojs#594]
When I try to load a .tpl file via xhr
```
const response = await fetch('components/main/views/main-view.tpl');
```
 I get a Status 200 with a json error:
```
{
    "error": "File extension: tpl is not supported"
}
```
Why would an xhr need to support file extensions?

Ubuntu 20.04

--- Global ---
Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0
neu CLI: v6.1.1

--- Project: ---
Neutralinojs binaries: v2.7.0
Neutralinojs client: v1.4.0

**Comment by shalithasuranga** [comment]
Hey.. you can find all the extensions at https://github.com/neutralinojs/neutralinojs/blob/921f3bd9b0fbf9def29ed6e085342defb50ec3dc/server/router.cpp#L155

This is not supported right now because the mime-type is not added there yet.  Btw are you trying to download this file or need to read it? If you need to read it you can use https://neutralino.js.org/docs/api/filesystem#filesystemreadfilereadfileoptions (for text files) and https://neutralino.js.org/docs/api/filesystem#filesystemreadbinaryfilereadbinaryfileoptions for binary files.

**Comment by shalithasuranga** [comment]
This issue was fixed. now any extension will work. Please check v3 once it's released.
