### ISSUE TITLE
Use of std::filesystem

### ISSUE THREAD

**Issue by theXnoob** [neutralinojs/neutralinojs#625]
Use of `std::filesystem` instead of Native Platform Api's for filesystem. Since the project is using C++17 we can use the `std::filesystem`

**Comment by shalithasuranga** [comment]
Hey.. thanks for the idea. FYI, we actually used filesystem before, but then used platform APIs due to some issues like:
- In C++17, it's in <experimental/filesystem>
- Had some execution issues on macOS, then fixed by removing <experimental/filesystem> uses.

For now, I am closing this issue maybe we can look back to <experimental/filesystem> if the current platform-specific implementation makes some issues.
