### ISSUE TITLE
Storage options

### ISSUE THREAD

**Issue by ranmacar** [neutralinojs/neutralinojs#649]
I'd love to have more options for storage. 

For example these shouldn't be hard to embed and would add very little to the binary:
- LMDB key-value db instead of the file-based .storage
- SQLite for an indexeddb upgrade.

**Comment by shalithasuranga** [comment]
Hey.. thanks for the ideas. I am closing this issue since now the extensions API can be used to write any custom backend code. Now we can use any database with any programming language. Please check more details here: https://neutralino.js.org/docs/how-to/extensions-overview The built-in storage APIs goal is to offer the same browser's LocalStorage to all supported modes in a portable way (once you copy the app, the storage data is also copied)
