### ISSUE TITLE
getting error when I try to load music

### ISSUE THREAD

**Issue by murunwas** [neutralinojs/neutralinojs#688]
**Expected Behavior**  
  I want to load music from local folder on my pc and play using `audio` tag
**Actual Behavior**  
I'm getting error shown below
![image](https://user-images.githubusercontent.com/8838943/140621049-6b30ca3c-0cbc-4bfa-adc8-a9e1b60227f9.png)

**Steps to Reproduce the Problem**  
 1. Paste this code on index.html
 ```
        <audio controls>
          <source src="path/to/mp3" type="audio/mpeg">
        Your browser does not support the audio element.
        </audio>
```

**Specifications**  
* NeutralinoJs Version: [Version number of NeutralinoJs framework]
* NeutralinoJs CLI version: [neu-cli version]
* Platform: [Platform specifications] 
-windows 10

**Comment by zvikasdongre** [comment]
That happened with me too... I searched a lot but couldn't find any solution...

**Comment by shalithasuranga** [comment]
Hey `file:` URI scheme won't work. Please load it directly from resources Eg: `<audio src="./audio/song.mp3"`. Neutralinojs has a built-in static file server like Apache HTTP server

**Comment by murunwas** [comment]
@shalithasuranga `<audio src="./audio/song.mp3"` only work for the file inside the `resources folder` but I want to browse and play files anywhere on my pc without copying them to `resources folder` first.

**Comment by danidre14** [comment]
Due to integrity and security issues, that is not allowed in browsers, so using a simple URL will not work.

Fortunately, Neutralino provides API to load files from your PC:
[OS.showOpenDialog](https://neutralino.js.org/docs/api/os#osshowopendialogtitle-options)

With it, you can navigate to the audio file that you want to play, and load it in (as a blob or binary), then convert it to a base64 representation and using `Audio` property or another, start listening to it.

**Comment by zvikasdongre** [comment]
@danidre14 can you please provide a example code snippet?

**Comment by shalithasuranga** [comment]
Closing this since the original issue has been answered. As @danidre14  mentioned, better to let users select files and initiate play. If you know the file location, you can read the binary file, then play the array buffer as explained in https://stackoverflow.com/questions/24151121/how-to-play-wav-audio-byte-array-via-javascript-html5

Thanks for reporting the issue and discussing
