### ISSUE TITLE
unable to open static file .js from react app build folder

### ISSUE THREAD

**Issue by judaristFullstack** [neutralinojs/neutralinojs#695]
**Expected Behavior**  
i want to use neutralino with my best frontent framework (react)
  
**neutralino Unable to open ./static/css/main.8c8b27cf.chunk.css**  
i'm try to code neutralino app with create react app and i Make the frontend framework's build path and Neutralino config's url, resourcesPath the same. but i get this error.

**Steps to Reproduce the Problem**  
 1. install neutralino app
 2. inside the app folder mkdir react-app and cd react app
 3. npx create-react-app
 4. yarn run build (for react app)
 5. neutralino.config.json ressourcesPath = react build path 
 "cli": {
    "binaryName": "neutralinojs-app",
   ** "resourcesPath": "/react-app/build/"**,
    "clientLibrary": "/resources/js/neutralino.js",
    "binaryVersion": "3.0.0",
    "clientVersion": "2.0.0"
  }
please how can i solve this ???

**Comment by shalithasuranga** [comment]
Hey.. Could you try to use "/react-app/build/" as the `url` (Neutralino config) and React app's base href as also the same value. 
Also, you can check this React-based app https://github.com/codezri/litepy

**Comment by shalithasuranga** [comment]
Hey @ithustle Please check this line https://github.com/codezri/litepy/blob/d4fb90aa12214e06029f3a70d06dac9882e34e64/litepy-rc/package.json#L5

Also, note that the next version of Neutralinojs doesn't need a base href from the React's side because of the new `documentRoot` property in the config https://github.com/neutralinojs/neutralinojs/blob/dbfb228c3e5eefdd63d11e208f45eedc3af82761/bin/neutralino.config.json#L6

**Comment by ithustle** [comment]
Thanks, @shalithasuranga

**Comment by shalithasuranga** [comment]
Closing the issue since it's already answered and we will release the `documentRoot` setting with v4
