### ISSUE TITLE
Unable to parse native call payload: Unknown exception api/debug/debug.cpp:16

### ISSUE THREAD

**Issue by ofceab** [neutralinojs/neutralinojs#788]
**Expected Behavior**  
Should return outputs of a command after call Neutralino.os.execCommand
  
**Actual Behavior**  
Currently returning **Unable to parse native call payload: Unknown exception api/debug/debug.cpp:16**

**Steps to Reproduce the Problem**  
 1.  Try it on windows. 
          let info = await Neutralino.os.execCommand('ping google.com');
          console.log(info);
 2. You won't get the console.log in dev tools console
 3. Stop the execution and see log in the terminal, you'll get the Error I noticed

**Specifications**  
* NeutralinoJs Version:4.2.0
* NeutralinoJs CLI version:  3.1.0
* Platform: Windows 11 Pro

**Comment by shalithasuranga** [comment]
Hey.. `ping` takes time to complete seems, Could you check with maybe another instant command, like `HELP`

**Comment by ofceab** [comment]
Sure sure 
I'll check that, then let you know

**Comment by ofceab** [comment]
Oh, It's the same issue even after try `ping -help`

**Comment by Blatman** [comment]
@shalithasuranga  -  FWIW - I get the same with Mac (using 10.13 bin build) (420/310).
  
Neutralino.os.execCommand('ping google.com') gives no return at all and blocks API.
Neutralino.os.execCommand('ping') works and gives return as below - 

<img width="996" alt="justping" src="https://user-images.githubusercontent.com/11089335/152307666-c73bf042-9fab-4d7d-a3b0-4847af900f24.png">

If I open a terminal then the google ping will respond almost straight away.

**Comment by Blatman** [comment]
@shalithasuranga - just found that if ping process is quit in activity monitor the ping results show in stdOut -

<img width="996" alt="pingquit" src="https://user-images.githubusercontent.com/11089335/152633365-4ef89ed1-f7c0-47ae-ad55-eeecce9ec410.png">

It should be noted that this API blocking also occurs in other execCommand scenarios eg:
starting a php web server will also block the API until the server process is quit.

Neutralino.os.execCommand('php -S localhost:8000 -t ' + NL_HOME + '/Sites/www')

Note:  still a problem with Neu 430/320

**Comment by ofceab** [comment]
Yes I noticed that also, this issue block other API

**Comment by Blatman** [comment]
@shalithasuranga - just went back and tried v280 and although the ping doesn't work with the url there is no API blocking.
It seems that the ping issue pre-dates the websocket implementation but the API blocking started with websocket.
Indeed if a php server is started in v280 it works fine with no blocking.
This is a problem with child processes that will not give a finite return.

<img width="1002" alt="nonblocking280" src="https://user-images.githubusercontent.com/11089335/153403154-c6aca9da-adb7-4f2c-9bf1-0ddd652f0399.png">

In the log above the output result for ping google.com was only returned when the ping process was quit in Activity Monitor.

**Comment by mark134340** [comment]
`await Neutralino.filesystem.readDirectory('F:/path/to')` Get the same log report.

**Comment by pathange-s** [comment]
Can someone confirm if this issue is specific to Windows and macOS only ? If it occurs on linux too, it would be easy for me to debug and find a fix. Else, I will get a Windows VM and test it out.

**Comment by pathange-s** [comment]
`os.execCommand` for API calls works perfectly. I am sure the below explanation should help with Windows and macOS as well.
@Blatman, you were using ping and when you execute it in the terminal, you have to press `crtl + c` to stop it.
When I checked under the hood, Neutralinojs returns the output once the execution is completely over. Since ping for any IP runs indefinitely, you were not getting the expected output.
But, if you consider running ping as `ping www.google.com -c 2`, the command execution stops after a definite amount of time, and you receive the desired output in the console.
To add, there's no API blocking as you mentioned earlier

![image](https://user-images.githubusercontent.com/76244077/167072683-0e0bed4b-d03f-4b30-a420-144d61911e62.png)


@mark134340, the `readDirectory` works perfectly in my case. Check below.

![image](https://user-images.githubusercontent.com/76244077/167071377-c16e235e-0131-43d7-98f4-be7ffa0a5672.png)

**Comment by Blatman** [comment]
@pathange-s  - yes correct, the only way to get the output via the child process method is to provide -c 2 or suchlike with the ping command. The Terminal usage is different in that the output will be returned to the screen continuously until the control-c is done whereas with the child process it will only provide the output if the ping process is killed ( or control-c somehow provided) unless -c is used.

I guess the answer is that the child process (execCommand) should not be used for a continuous ping unless -c x is specified otherwise it will give no streaming output and block the API.

**Comment by mark134340** [comment]
@pathange-s  Yes, it works when using relative paths, but not when using absolute paths. I use windows10 Pro 21h2

**Comment by pathange-s** [comment]
@Blatman exactly! That's how the underlying architecture is working currently. Once the command completes/exits, we obtain the output.

**Comment by pathange-s** [comment]
@mark134340 It works fine with both absolute and relative paths. Please check the below-attached images.
Make sure to pass the path in the correct way. (Check [this](https://github.com/neutralinojs/neutralinojs-cli/blob/fdbee9975029871bf04f871c5e91b3626a2b979c/src/utils.js#L41-L43))
- Absolute Path:

![image](https://user-images.githubusercontent.com/76244077/167093079-4a1ddf0a-af70-40a6-bb95-765ff3159a0e.png)

- Relative Path:

![image](https://user-images.githubusercontent.com/76244077/167093127-caa2707d-cbdd-4a28-b5a8-d4e654774e22.png)

**Comment by mark134340** [comment]
@pathange-s 
![image](https://user-images.githubusercontent.com/42252827/167097897-398e5b6a-8d92-4a9a-be7d-d7869c9539ef.png)
![image](https://user-images.githubusercontent.com/42252827/167097988-fcf9aac7-922d-4b5c-9c36-aa2b100108ee.png)
I don't know why

**Comment by pathange-s** [comment]
@mark134340 What error is being thrown ? I am using the same version of binary and client.

**Comment by mark134340** [comment]
@pathange-s 
No errors were thrown, just recorded in the log report.
![image](https://user-images.githubusercontent.com/42252827/167107049-b094c29a-7a35-41fb-9f0b-1b50cc81c466.png)

**Comment by pathange-s** [comment]
@mark134340 please consider joining the discord server for faster replies. I will try to check the log report and will get back to you.

**Comment by mark134340** [comment]
@pathange-s OK! Thanks

**Comment by shalithasuranga** [comment]
Hey.. thanks for reporting the issue and discussing it further. Closing this issue since now we have the `Neutralino.os.spawnProcess` function for handling long-running processes that `execCommand` cannot handle without waiting.

Thanks :tada:
