### ISSUE TITLE
Completely portable executables

### ISSUE THREAD

**Issue by soshimee** [neutralinojs/neutralinojs#789]
**Expected Behavior**  
There should be a way to only produce the binaries, without `resources.neu` and `WebView2Loader.dll`.

**Actual Behavior**  
There isn't one for some reason, and I'm stuck with having to have multiple files for it to run.

**Steps to Reproduce the Problem**  
 1. Build

**Specifications**  
* NeutralinoJs Version: v4.2.0
* NeutralinoJs CLI version: v3.1.0
* Platform: All, especially windows because of `WebView2Loader.dll` file.

**Comment by soshimee** [comment]
What I'm doing currently is using iexpress to make self-extracting executables.

**Comment by molten-firescar96** [comment]
@Tazeg you don't have to be rude, shalithasuranga is providing this tool for free. If they haven't found the time to make every feature yet that's understandable. As is Neutralino is still useful to others as an electron alternative.

**Comment by Tazeg** [comment]
I didn't want to be rude. I would just like to report that the EXE built with Neutralino is not a portable application. You should work on this to be a true Electron alternative.

**Comment by DEVLOPRR** [comment]
Even if we found a way to produce a single binary, there are some problems we will face.

Since You Need 1 Binary Which Contains Everything you'll need to install Microsoft C++ Build Tools on Windows, or g++ or gcc on Linux, with which you'll need to install some libraries on Linux and then you'll need to wait 10 to 15 minutes for Building your binary.

You'll also need a way to somehow put that `resource.neu` file inside the executable. the `resource.neu` file contains all your frontend HTML, CSS and JS Code in a archive format. if you need a single binary, you'll need to put that file somehow inside the binary.

And for the `WebView2Loader.dll` we are looking onto it.

**Comment by soshimee** [comment]
I thought there were ways of packaging archives into executables? Either they were hacks or official, idk.

**Comment by DEVLOPRR** [comment]
can you list some ways?

**Comment by soshimee** [comment]
`iexpress`?

**Comment by shalithasuranga** [comment]
Closing this since we have #1120 with detailed content to cover the same request. Thanks for reporting this and discussing :tada:
