### ISSUE TITLE
Window not hiding if execCommand is not resolved

### ISSUE THREAD

**Issue by preraksola** [neutralinojs/neutralinojs#810]
In my Nuetralino app, I need to execute a command. So for that, I am using `execCommand`. If there is an error, the command terminates and resolves the promise with the error string. If not, it will keep on running and so the promise never gets resolved.

After `execCommand`, I have a setTimeout() that executes some piece of code after 10 seconds. In this, I am calling `window.hide()` method to close the app window. However, it does not work if the `execCommand`'s promise is not resolved.

So, is there a way that I can close the window even when my command is still running?

**Expected Behavior**  
Execute other native commands even if the process called via `execCommand` is still running.
  
**Actual Behavior**  
No effect on the application if `window.hide()` is called after `os.execCommand`. 

**Steps to Reproduce the Problem**  
 1. Install openconnect on Ubuntu: `sudo apt install openconnect`
 2. Add the following code on a button click
 ```js
let cmd = "{ printf 'ZeeTim000\n'; } | sudo openconnect 135.125.24.59:9443 --servercert pin-sha256:7G90JZhYxeW2ihUpptPk37vOVYJSTn8WuOCJq2WnxHM= --passwd-on-stdin --user test --syslog"
Neutralino.os.execCommand(cmd).then((res) => {
    console.log(res);
}).catch((err) => {
	console.log("error block", err);
});

setTimeout(() => {
	Neutralino.window.hide();
}, 10000);
``` 

**Specifications**  
* Neutralinojs binaries: v4.3.0
* Neutralinojs client: v3.2.0
* NeutralinoJs CLI version: 9.2.0
* Platform: Ubuntu

**Comment by DEVLOPRR** [comment]
If you try running this code:

```javascript
Neutralino.os.execCommand("ping -c 10 google.com").then(res => {
	console.log("RES: ", res);
}).catch(err => {
	console.error("ERROR: ", err);
})

setTimeout(() => {
	Neutralino.window.hide();
}, 2000)
```

here the window won't hide after 2 seconds, instead after the `execCommand` has been resolved, then the window will hide, that's why your window never hided, because the `execCommand` didn't resolve.

why so?

currently when you call the `execCommand`, it will execute that piece of command in native shell and then it will return the values.

all of this is asynchronous, which means your javascript code will not be blocked, but the process which handles the API calls isn't asynchronous.

that's why when your window doesn't hides because the process handling the APIs is already busy handling the `execCommand`.

Let's see if in future it is fixed or not.

**Comment by preraksola** [comment]
@DEVLOPRR Makes sense. Thank you for the details.

To bypass this, I added `background: true` while launching the command and I added file redirection in my command so that I can read the output from that file after some time.

```js
Neutralino.os.execCommand("ping -c 10 google.com >> /tmp/test.log", {background: true}).then(res => {
    console.log("RES: ", res);
}).catch(err => {
    console.error("ERROR: ", err);
})

setTimeout(() => {
    //Read /tmp/test.log file data
    Neutralino.window.hide();
}, 2000)
```

However, in this scenario, the file gets created but it does not contain any output.

**Comment by Blatman** [comment]
This issue is probably the same as #788 - the execCommand api will not handle a streaming return. The background true indeed resolves the promise with no further return of ongoing data. There needs to be a way of the execCommand to receive data until complete or either end terminates the connection. Maybe spawnCommand type of API would be better that would support streaming (similar to the node child process spawn).

**Comment by shalithasuranga** [comment]
Please note that we have `os.spawnProcess` in the [roadmap](https://github.com/neutralinojs/roadmap).

**Comment by shalithasuranga** [comment]
Hey all.. the new process spawning feature was implemented -- you can check more details from here: https://github.com/neutralinojs/neutralinojs/blob/main/CHANGELOG.md#api-process-spawning-api

We will release spawning API with the next release soon, but you can experiment anytime with the `nightly` version ;)

Thanks :tada:
