### ISSUE TITLE
Is indexdb supported?

### ISSUE THREAD

**Issue by delebash** [neutralinojs/neutralinojs#825]
My current app saves and loads to indexdb and works fine in a normal webserver node env.  After compiling it with neutralinojs everything works except loading data from indexdb

**Comment by hv6erT** [comment]
As I know neutralino js is not typical browser like electron js or nw.js. Neutralino run server that expose native api and run your html, css and js in default system webview. Webviews has not any instances so data saved to IndexedDB, localstorage, WebSQL cannot be loaded next time. Instead of this you should to use Neutralino storage. You can read more here: [Neutralino Storage API](https://neutralino.js.org/docs/api/storage)

**Comment by delebash** [comment]
Thanks for the info.  I really like this product, it easy to use and setup.  However, I ended up going with https://github.com/tauri-apps/tauri.  As far as I understand tauri also uses a WebView and indexdb just worked.  It was a little more difficult to setup though.

**Comment by wll8** [comment]
Which release implements this feature? Although this issue is closed, it is not associated with the corresponding commit.
