### ISSUE TITLE
url query strings not supported

### ISSUE THREAD

**Issue by jefftanooki** [neutralinojs/neutralinojs#826]
**Expected Behavior**  
A page link containing a query string should still navigate to that page. Then secondly, that query string should hopefully make its way into GET variable.
  
**Actual Behavior**  
Clicking the link does nothing and produces an error in the log.
> ERROR 2022-03-09 12:13:12,500 Unable to open ./resources/open.html?hey=hello api/debug/debug.cpp:16

**Steps to Reproduce the Problem**  
 1. in documentRoot, create an index.html file and an open.html file. give both a proper html skeleton.
 2. in index.html, add an anchor tag containing a link to open.html that also has a query string `<a href="open.html?foo=bar">click me</a>`
 3. in open.html, just have a simple paragraph tag to announce that open.html is currently being displayed.
 4. build/run the app and click on the link. nothing happens.
 5. removing `?foo=bar` from the url solves the issue.

**Other Information**
Using a query string in a stylesheet for the common purpose of cache busting also results in an error similar to the above, and the stylesheet is not loaded at all. ie, `<link rel=stylesheet type=text/css href="css/style.css?v=0.9.5">`

**Specifications**  
* NeutralinoJs Version: 4.3.0 (binary version)
* NeutralinoJs CLI version: 3.2.0
* Platform: Windows 10

**Comment by shalithasuranga** [comment]
Hey @jefftanooki Thanks for reporting this issue. Now we can load resources with any arbitrary query parameter -- the static server will ignore query params and load the resource as usual. However, we don't have a proper caching support in the static server yet. For example, if the browser requests a resource several times, the static server will use the HTTP code `200`, not `304`. We will check about it in the future. Now, I am closing the issue since query parameters can be used.

This fix will be released with the next version, but you can test using the `nightly` version anytime :)

**Comment by itsuifeng** [comment]
Specifications:
NeutralinoJs Version:6.0.0 (binary version)
NeutralinoJs CLI version: 6.0.0
Platform: Windows 10

eg:
<link rel=stylesheet type=text/css href="css/style.css?v=0.9.5">

bug: style.css can not be loaded。

**Comment by itsuifeng** [comment]
Specifications:
NeutralinoJs Version:6.0.0 (binary version)
NeutralinoJs CLI version: 6.0.0
Platform: Windows 10

eg: ```<link rel=stylesheet type=text/css href="css/style.css?v=0.9.5">```

bug: style.css can not be loaded。
