### ISSUE TITLE
Document or fix `url` param for `window.create`

### ISSUE THREAD

**Issue by APTy** [neutralinojs/neutralinojs#863]
Hello! I'm a new user of neutralino and I have to say I'm really loving it so far. I had one issue I came across that I didn't see documented anywhere yet, so I figured I'd post about it for anyone it may help in the future. :pray:

**Describe the bug**
If you call `window.create()` using a `url` without a leading slash (e.g. `index.html`) instead of with a leading slash (e.g. `/index.html`) you will receive a nonspecific error: `The application can't be opened.`

**To Reproduce**
1. Call `Neutralino.window.create('index.html')`

**Expected behavior**
I sort of expected the `/` to be optional, but either way, docs could be updated to say it's required, or the requirement can be lifted.

**Screenshots/Screen recordings**
<img width="260" alt="Screen Shot 2022-04-14 at 9 01 22 PM" src="https://user-images.githubusercontent.com/9010671/163516417-eeac2af5-706e-4208-8ef7-d0b44b3fdaae.png">

**Specifications**  
 - OS: OS X 11.5.2
 - Neutralinojs binaries: v4.4.0
 - Neutralinojs client: v3.3.0
 - Project version: v1.0.0

**Comment by shalithasuranga** [comment]
Hey.. thanks for reporting this issue. Yeah, we need to add the `/` prefix since we tried to map Neutralinojs file paths to normal static file server paths. Closing this since it is now documented already: https://neutralino.js.org/docs/api/window#parameters-6

We will think further about your suggestion to make `/` part optional (Need to check how it affects other parts of the framework)

Thanks :tada:
