### ISSUE TITLE
Blank UI when running windows build

### ISSUE THREAD

**Issue by mike-kaonashi** [neutralinojs/neutralinojs#958]
**Describe the bug**
Got blank UI when running execute file (Windows).

**To Reproduce**
1. run `neu build` to get the execute file
2. Zip the build folder and move it to raw enviroment (VM environment) to make sure the environment 100% fresh
3. Run the execute file
4. Got the blank UI instead cuz of the loopback localhost not enabled yet (https://help.hcltechsw.com/appscan/ADAC/9.0.3/en-US/r_LoopbackForEdge.html)

**Expected behavior**
The build version must be runnable on a totally fresh environment (Windows)

**Specifications**  
 - OS: Windows 10 Enterprise x64
 - Neutralinojs version: 4.6.0
 - Neutralinojs client library version: v3.5.0
 - Neutralinojs CLI version: v9.3.1

**Additional context**
So then Are there any ways to check and enable the localhost loopback before running the application?
and also the log file doesn't record anything if webview can't render the UI.

**Comment by kolbasa** [comment]
I was just about to create the same bug ticket.
Here is a screenshot to go with it:

![Bildschirmfoto 2022-07-20 um 11 24 01](https://user-images.githubusercontent.com/3901582/179965130-5c5093ea-1b49-4949-8cb0-53091ee9428c.png)

I guess the problem is that Windows 10 doesn't come bundled with WebView2.
This complicates the use of Neutralino.js.
You suddenly have to take care of the WebView installation yourself. Other frameworks take care of this step (e.g. tauri).

@[mike-kaonashi](https://github.com/mike-kaonashi)
Here is the link to the [Webview2](https://developer.microsoft.com/de-de/microsoft-edge/webview2/) installation file.
