### ISSUE TITLE
neutralino.config.json file is missing or corrupted

### ISSUE THREAD

**Issue by shandbb** [neutralinojs/neutralinojs#964]
Neutralinojs in MacOS version 12.5, when the packaged binary files are copied to other locations, run the prompt
<img width="413" alt="image" src="https://user-images.githubusercontent.com/110076762/181150222-ca229f73-2050-46cc-84da-083e389ce266.png">

**Comment by shandbb** [comment]
_   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
neu CLI: v9.3.1

--- Project: (js.neutralino.sample) ---
Neutralinojs binaries: v4.7.0
Neutralinojs client: v3.6.0
Project version: v1.0.0

**Comment by Aworldc** [comment]
I'm on windows and had this issue. Did you also copy `resources.neu` into that folder? Annoyingly neutralino doesn't build them into the binary.

**Comment by garv-shah** [comment]
I have `resources.neu` in the same directory, but it still doesn't seem to be able to run

**Comment by cmkrist** [comment]
Still an issue

**Comment by peteygao** [comment]
Ditto, also having this issue on M1 MacBook Pro running 12.7. Given the lack of activity or response in this thread, it doesn't look like the package maintainers care about macOS distribution, which is too bad. Neutralino.js is by far the fastest build/dev experience I've had (compared to Tauri or Electron).

Side note, this was an issue in the past and allegedly it was "fixed" https://github.com/neutralinojs/neutralinojs/issues/652, but it either wasn't fixed or the issue has come back.

For what it's worth, the binary works fine on Linux (Ubuntu 22.04) 🤷🏼‍♂️...

**Comment by jerrygreen** [comment]
Still an issue. Windows 10

I don't understand how to pass arguments to neutralino binaries. `neu` cli works perfectly, but I would like to pass custom config to separate development/production workflows. `neu` cli doesn't have such an option, unfortunately. Neutralino binaries seem to have such an option, but it simply doesn't work, due to this issue. If I would know better, of how exactly `neu` cli does this... But from the source code I cannot find where and how it passes arguments exactly, there's some dynamic code through other libraries, not helping to understand this at all. It should be possible, obviously, since it works somehow when executed from `neu` – it just doesn't work when binaries called manually in bash :\

**Comment by Aworldc** [comment]
> Still an issue. Windows 10
> 
> I don't understand how to pass arguments to neutralino binaries. `neu` cli works perfectly, but I would like to pass custom config to separate development/production workflows. `neu` cli doesn't have such an option, unfortunately. Neutralino binaries seem to have such an option, but it simply doesn't work, due to this issue. If I would know better, of how exactly `neu` cli does this... But from the source code I cannot find where and how it passes arguments exactly, there's some dynamic code through other libraries, not helping to understand this at all. It should be possible, obviously, since it works somehow when executed from `neu` – it just doesn't work when binaries called manually in bash :\
> 
> Maybe it's something related to relative paths, like it's trying to seek config nearby executables, not from the current folder? Idk.

I don't know exactly what you're trying to do, but it sounds like you are trying to tell neutralino what to do using command line flags (like in [here](https://neutralino.js.org/docs/cli/internal-cli-arguments/)). if so, try creating a neutralino.config.json with the following contents: `{"applicationId": "net.example.something","url":"about:blank","defaultMode":"window"}`

**Comment by shalithasuranga** [comment]
Closing this since the latest framework (will be released within this month) continues the loading process even if the configuration file doesn't exist. However, make sure that the `resources.neu` file is present near the app binary, otherwise, Neutralinojs will be loaded with a default configuration :) Thanks so much for reporting this and starting a discussion based on it :tada:
